const MonsterData = [
    {
    name: "Wendigo",
    prey: "Humans, feed on human flesh to survive.",
    appearance: "Humanoid, can be over 6 feet, eyes are pushed back deep in their sockets, and have many layers of crooked, sharp, teeth, razor-like claws used to rip prey to shreds, sometimes said to have matted fur and have chunks of skin and flesh missing, due to consumption.",
    abilities: "Voice mimicry, immortality, super speed, superhuman strength, super agility, super senses, super stamina.",
    weaknesses: "Fire, anasazi symbols, iron, steel, silver.",
    photo:"https://www.fanbolt.com/storage/2022/02/wendigo-supernatural.jpg"
    },
    {
    name: "Djinn",
    prey: "Humans, feed on human blood while keeping the in a coma-like state.",
    appearance: "Humanoid creatures with tattooed skin.",
    abilities: "Hallucinogenic Touch, pyrokinesis, telepathy, super strength, super speed, Shapeshifting, immortality, super agility.",
    weaknesses: "Siver and lamb blood.",
    photo: "https://thewinchesterfamilybusiness.com/images/SeasonTwo/WIAWSNB/Djinn.JPG"
    },
    {
    name: "Vampire",
    prey: "Usually feed on human blood, but can survive on animal blood.",
    appearance: "Human appearance, sharp, pointed, retractable teeth, can some times have sharp fingernails as well.",
    abilities: "Super strength, fangs, super speed, super agility, super sense, immortality, regeneration, super stamina and stealth.",
    weaknesses: "Dead man's blood, sunlight, decaptation.",
    photo: "https://www.grunge.com/img/gallery/things-supernatural-gets-wrong-about-mythical-beings/vampires-down-for-the-count-1567699945.jpg",
    },
    {
    name: "Wraith",
    prey: "Humans, drain and feed on brain fluid from their victims.",
    appearance: "Can look like humans, their true form is a humanoid creature with rotten skin. Their true form can be seen when reflected on a mirror.",
    abilities: "Perception altering, insanity inducement, retractable spikes, invulnerability, super strength, super agility, regeneration.",
    weaknesses: "Silver, mirros, spike braking, severe trauma.",
    photo: "https://tv-fanatic-res.cloudinary.com/iu/s--KteU5kvd--/t_slideshow/cs_srgb,f_auto,fl_strip_profile.lossy,q_auto:420/v1548984746/slides/3453/wraith.jpg",
    },
    {
    name: "Shapeshifter",
    prey: "Don't have a specifc prey that needs to survive but sometimes use their abilities to kill people.",
    appearance: "Look like humans, eyes glow when in cameras on light rays cross their eyes.",
    abilities: "Shapeshifting in to another human, regenaration, telepathy, voice mimicry, super strength, super speed, super agility.",
    weaknesses: "Silver, decaptation, heart extraction.",
    photo: "https://pm1.narvii.com/6415/36b56adcc6120cef92b7707c5ba8ae42e7321092_hq.jpg",
    },
    {
    name: "Werewolves",
    prey: "Feed on human flesh, always eating the heart, can survive feeding only of animals.",
    appearance: "Humanoid, combination of humans and wolves, has claws and fangs.",
    abilities: "Transform into a wolf-like creacture under a full moon, infectious bite, super strength, agility, super stamina and speed, super sense, regeneration.",
    weaknesses: "Silver, decaptation.",
    photo: "https://i.pinimg.com/originals/1d/1b/7b/1d1b7b0adc859a199d1714fa7bdb3482.jpg",
    },
    {
    name: "Siren",
    prey: "They do not feed on humans, but feel an intense rush of pleasure when their victims do acts of violence, and even kill for then, and move on to the next victim.",
    appearance: "Can look like human, true form is a hairless, vaguely-humanoid creature.",
    abilities: "Telepathy, shapeshifting into what the victim most want, venom spit.",
    weaknesses: "Bronze daggercoated in the blood of victim.",
    photo: "https://64.media.tumblr.com/59e69a2f44a65093ce6e634602053aad/tumblr_inline_po460dexX01ryf7k8_500.jpg",
    },
    {
    name: "Pishtaco",
    prey: "Feed of human fat but don't have to kill the victim.",
    appearance: "Look human, have a elongated sucking appendage taht they release from their mouth when they feed.",
    abilities: "Super strength, feed on human fat.",
    weaknesses: "Silver, cutting off their sucking appendage.",
    photo: "https://thesupernaturalfoxsisters.files.wordpress.com/2015/06/pishtacospn.jpg",
    },
    {
    name: "Skinwalker",
    prey: "Can use their abilities to harm others.",
    appearance: "Humans that can shape shift into an animal.",
    abilities: "Enhanced strenth, super speed, accelerated healing, super senses, shapeshifting.",
    weaknesses: "Silver",
    photo: "https://i.pinimg.com/originals/47/ba/c4/47bac476fba637914e7c2b6ed4274069.jpg",
    },
    {
    name: "Rugaru",
    prey: "Once they have human flesh for the first time they change into predators and attack humans.",
    appearance: "Humans taht have a genetic condition and in their adult life develop a hunger for human flesh, after feeding gets violent and start changing its appearence.",
    abilities: "Super strength, super speed, super stamina, super senses.",
    weaknesses: "Fire.",
    photo: "https://pm1.narvii.com/6118/bcf709fe2fe9cb7d64712dbd375a1bba43250f78_hq.jpg",
    },
    {
    name: "Khan worms",
    prey: "Posses humans and control their actions.",
    appearance: "Brown worm with two large black curved fangs.",
    abilities: "Possession by getting inside people's head through the ear, super strength, super agility.",
    weaknesses: "Electrocution, extreme dehydration, been crush.",
    photo: "https://nautiluslive.org/sites/default/files/styles/responsive_image_sm/public/images/2014-10/chekovs_ear-ceti_eel.jpg?itok=D0SR5O_6",
    },
    {
    name: "Kitsune",
    prey: "Feed of human's pituitary glands.",
    appearance: "Look like humans, can shift into a fox like humanoid.",
    abilities: "Super strength, super speed, claws, shapeshifting.",
    weaknesses: "Heart destruction, starvation.",
    photo: "https://www.gateworld.net/wp-content/uploads/2019/03/supernatural_staite.jpg",
    },
    {
    name: "Dragon",
    prey: "Usually virgin women.",
    appearance: "Can take human form, have large wings, large talons and snake-like eyes.",
    abilities: "Super strength, shapeshifting, pyrokinesis. flight, super speed and stamina, super senses, immortality.",
    weaknesses: "Dragon-killing swords.",
    photo: "https://i.imgur.com/0WSryuz.jpeg",
    },
    {
    name: "Ghost",
    prey: "Go after people they have unfinished busines or people that have a specific trait of personality.",
    appearance: "Appear in the form of the physical body, but look pale and sickly.",
    abilities: "Electromagnetic interference, thermokinesis, invisibility, telekinesis, teleportation, super strength, astral perception, environment manipulation.",
    weaknesses: "Salt, iron, salt and burn remains, destroying hunted object.",
    photo: "https://m.media-amazon.com/images/M/MV5BOGQ5MWFmY2ItY2UxNS00MTQwLWE0MGItMzU1Zjg0ZDg1NWUyXkEyXkFqcGdeQXVyNjYyMTc1ODY@._V1_.jpg",
    },
    {
    name: "Demon",
    prey: "Can go after humans for fun, or target someone for some specific reason.",
    appearance: "Black smoke, when possed a human their eyes can look black, yellow, red or white.",
    abilities: "Possession once enter in a human's body, Super strength, magic powers, teleportation.",
    weaknesses: "Holy water, colt, angel blade, exorcism rituals.",
    photo: "https://medias.spotern.com/spots/w640/9/9444-1571237541.jpg",
    },
    {
    name: "Hellhound",
    prey: "Usually go after humans that made a deal with a demon to kill when it's time, can also go after someone once their owner demon commands. ",
    appearance: "Ferocious black dogs with red eyes.",
    abilities: "Invisibility, super senses, tracking, immortality.",
    weaknesses: "Salt, goofer dust, devil's shoestring.",
    photo: "https://s3-us-west-2.amazonaws.com/files.geekgirlauthority.com/wp-content/uploads/2017/03/Supernatural-S1215g.jpg",
    },
];

export default MonsterData;